spring.application.name=LevelUp

# Server configuration
server.port=8080

# ===============================
# MySQL Database Configuration
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/LvlUp_DB?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root

# ===============================
# JPA / Hibernate Configuration
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true

# AI Configuration (Use the key from Google AI Studio)
# Replace with your actual key or set as environment variable
spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.options.model=gemini-1.5-flash

#=================================================================================
# Logging Configuration
# ---------------------------------------------------------------------------------
# Root Log Level
logging.level.root=INFO
# Package-Specific Log Levels
logging.level.org.hibernate.SQL=ERROR
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.springframework.security=INFO
logging.level.org.springframework.boot.actuate=INFO
# ---------------------------------------------------------------------------------
# Console Logging Pattern
logging.pattern.console=%d{yyyy-MM-dd hh:mm:ss.SSS a} %highlight(%5level) %green([%logger{36}]) - %M - %msg%n
# ---------------------------------------------------------------------------------
# File Logging Configuration
logging.file.path=AppLog
#logging.file.name=AppLog/log-%d{yyyy-MM-dd_HH-mm-ss}.log
logging.rollingpolicy.file-name-pattern=${logging.file.path}/log-%d{yyyy-MM-dd_HH-mm-ss}.%i.log
logging.rollingpolicy.max-file-size=5MB
logging.rollingpolicy.total-size-cap=2GB
logging.rollingpolicy.max-history=365
logging.rollingpolicy.clean-history-on-start=false
logging.rollingpolicy.compress=false